name: restaurant
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.3 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  http: ^1.3.0
  sqflite: ^2.3.0
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^17.2.2
  flutter_timezone: ^4.1.0
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
